server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/your-database
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 121@Shivam
  
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true

logging:
  level:
    com.queuemanagement: DEBUG

app:
  base-url: http://localhost:3000
  frontend-url: http://localhost:3000